### ISSUE TITLE
Activity chart only pulling one record's data

### ISSUE THREAD

**Issue by LunaAsefaw** [kartoza/sawps#1852]
This is the data, which means there was 16 intake for 2023:
![image](https://github.com/kartoza/sawps/assets/90245715/bf8f9b96-0015-4ed3-b612-f3d53167f898)

This is the chart:
![image](https://github.com/kartoza/sawps/assets/90245715/9d43e22b-7e64-44e1-9f6b-e375ec43c9c3)

The expected output:
n=16
%= (16/1358)*100=1.178% and not 15.56.
Remember that activity % is the total activity count divided by the total population for that species (which will be all the properties, not just the selected property, right @amyburness @dimasciput @timlinux ?). If it is just the selected properties then the current calculation for % is correct but the count displayed is wrong

![image](https://github.com/kartoza/sawps/assets/90245715/3c955f51-6f83-4cb9-b8bc-46b7723f7141)

**Comment by dimasciput** [comment]
@LunaAsefaw should be for selected properties. Yes we should fix the table.

**Comment by LunaAsefaw** [comment]
@dimasciput The purpose of the chart is to show how much of the total population was perhaps imported and exported so if the data from this chart is filtered by activity, it will only pull data from properties that had the selected activity and the output will be exaggerated (I could be terribly wrong though). See the video for what I mean

Uploading 2023-12-12 10-01-25.mp4…

**Comment by LunaAsefaw** [comment]
Revised @danangmassandy :
keep the percentage calculation as is.
However, the value of n is still wrong. When there is no activity filter, n=2, it should be n=16.
Then when the filter is selected, n=14, it should still say n=16 because the sum of all the intake for that year will not change. Just the percentage will change between when you use all data or a selected few
![image](https://github.com/kartoza/sawps/assets/90245715/fc455efc-8a98-4150-8804-463c7884f998)


Also what is the mark here:
![image](https://github.com/kartoza/sawps/assets/90245715/1c4b089a-b797-4bf8-a558-5f73aac551eb)
